# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.1
executors:
  custom:
    docker:
      - image: "cypress/base:16.18.1"
    environment:
      TZ: "Europe/Berlin"

workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: npm test
          executor: custom
          build: "npm run build"
